name: Build project

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    # Skip all jobs if PR is in draft
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v4

      - uses: atopile/setup-atopile@main

      - run: ato sync
      - run: ato build
        id: build
        continue-on-error: true

      - name: Upload Combined Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

      - name: Check build status
        if: steps.build.outcome == 'failure'
        run: exit 1
